### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by Ccaa1995** [smallXueTu/LTCraft-src#4]
Hello friend you have discord or twitter?
i need to ask some questions..
Thanks!

**Comment by smallXueTu** [comment]
Have what problem can ask questions here, twitter we don't.

**Comment by Ccaa1995** [comment]
Ahh okay..
It is not about plugin errors ..
I was wondering if you make plugins on a commission basis?

**Comment by smallXueTu** [comment]
> Ahh okay..
> It is not about plugin errors ..
> I was wondering if you make plugins on a commission basis?

可以，这个问题可以通过推特交流

**Comment by smallXueTu** [comment]
> Ahh okay..
> It is not about plugin errors ..
> I was wondering if you make plugins on a commission basis?

Yes, this problem can communicate via twitter

**Comment by Ccaa1995** [comment]
Okay..
What is your Twitter for contact?

**Comment by smallXueTu** [comment]
> Okay..
> What is your Twitter for contact?

https://twitter.com/1asIFxQuQfD5Yz5

**Comment by Ccaa1995** [comment]
Okay, thanks!
